name: 自动爬取IPTV地址
on:
  schedule:
    - cron: '0 1 * * *'  # 每天UTC时间1点（北京时间9点）执行
  workflow_dispatch:  # 手动触发开关

jobs:
  crawl-iptv:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 执行爬虫
        run: python iptv_crawler.py

      - name: 提交更新后的m3u8文件
        run: |
          git config --global user.name "Gitee Actions"
          git config --global user.email "actions@gitee.com"
          git add iptv_list.m3u8
          git commit -m "自动更新IPTV地址 $(date +'%Y-%m-%d %H:%M:%S')" || echo "无更新内容"
          git push
